services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn reporting_service.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
